CREATE TABLE CIDADE (
CD_CIDADE INTEGER NOT NULL PRIMARY KEY,
DS_CIDADE VARCHAR(50) NOT NULL,
DS_UF CHAR(2)
);

CREATE TABLE PESSOA (
CD_PESSOA INTEGER NOT NULL PRIMARY KEY,
DS_PESSOA VARCHAR(50) NOT NULL,
TP_PESSOA CHAR(1),
CD_CIDADE INTEGER NOT NULL,
FOREIGN KEY (CD_CIDADE) REFERENCES CIDADE (CD_CIDADE)
);

CREATE TABLE PRODUTO (
CD_PRODUTO INTEGER NOT NULL PRIMARY KEY,
DS_PRODUTO VARCHAR(50) NOT NULL,
VL_PRODUTO NUMERIC(8,2) NOT NULL,
QT_ESTOQUE INTEGER NOT NULL
);

CREATE TABLE OPERACAO (
CD_OPERACAO INTEGER NOT NULL PRIMARY KEY,
DS_OPERACAO VARCHAR(50) NOT NULL,
TP_OPERACAO CHAR(1) NOT NULL,
IN_ESTOQUE INTEGER NOT NULL,
IN_FINACEIRO INTEGER NOT NULL
);

CREATE TABLE NF (
CD_NF INTEGER NOT NULL,
CD_PESSOA INTEGER NOT NULL,
NR_SERIE INTEGER NOT NULL,
CD_OPERACAO INTEGER NOT NULL,
DT_NF DATE NOT NULL,
CD_OS INTEGER NOT NULL,
VL_TOTAL NUMERIC(8,2) NOT NULL,
PRIMARY KEY (CD_NF,CD_PESSOA,NR_SERIE),
FOREIGN KEY (CD_PESSOA) REFERENCES PESSOA (CD_PESSOA),
FOREIGN KEY (CD_OPERACAO) REFERENCES OPERACAO (CD_OPERACAO)
);

CREATE TABLE NF_PRODUTO (
CD_NF INTEGER NOT NULL,
CD_PRODUTO INTEGER NOT NULL,
CD_PESSOA INTEGER NOT NULL,
NR_SERIE INTEGER NOT NULL,
VL_PRODUTO NUMERIC(8,2) NOT NULL,
QT_PRODUTO INTEGER NOT NULL,
PRIMARY KEY (CD_NF, CD_PRODUTO, CD_PESSOA, NR_SERIE),
FOREIGN KEY (CD_NF, NR_SERIE, CD_PESSOA) REFERENCES NF (CD_NF, NR_SERIE, CD_PESSOA),
FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO (CD_PRODUTO)
);

CREATE TABLE PARCELA (
CD_PARCELA INTEGER NOT NULL,
CD_NF INTEGER NOT NULL,
CD_PESSOA INTEGER NOT NULL,
CD_PRODUTO INTEGER NOT NULL,
NR_SERIE INTEGER NOT NULL,
VL_PAGAMENTO NUMERIC(8,2) NOT NULL,
VL_PAGAR NUMERIC(8,2) NOT NULL,
DT_PAGO DATE NOT NULL,
DT_PAGAR DATE NOT NULL,
CD_REPARCELA INTEGER NOT NULL,
PRIMARY KEY (CD_PARCELA, NR_SERIE, CD_PESSOA, CD_NF),
FOREIGN KEY (NR_SERIE, CD_PESSOA, CD_NF) REFERENCES NF (NR_SERIE, CD_PESSOA, CD_NF)
);

CREATE TABLE FORMA_PAGAMENTO (
CD_FORMA INTEGER NOT NULL PRIMARY KEY,
DS_FORMA VARCHAR(50) NOT NULL,
NR_PARCELAS INTEGER NOT NULL,
IN_ENTRADA CHAR(1) NOT NULL,
NR_INTERVALO INTEGER NOT NULL
);

CREATE TABLE OS (
CD_OS INTEGER NOT NULL PRIMARY KEY,
CD_PESSOA INTEGER NOT NULL,
CD_FORMA INTEGER NOT NULL,
DT_OS DATE NOT NULL,
IN_SITUACAO CHAR(1) NOT NULL,
FOREIGN KEY (CD_PESSOA) REFERENCES PESSOA (CD_PESSOA),
FOREIGN KEY (CD_FORMA) REFERENCES FORMA_PAGAMENTO (CD_FORMA)
);

CREATE TABLE SERVICO (
CD_SERVICO INTEGER NOT NULL PRIMARY KEY,
DS_SERVICO VARCHAR(50) NOT NULL,
VL_SERVICO NUMERIC(8,2) NOT NULL,
DT_CADASTRO DATE NOT NULL,
IN_SITUACAO CHAR(1)
);

CREATE TABLE OS_SERVICO (
CD_SERVICO INTEGER NOT NULL,
CD_OS INTEGER NOT NULL,
QT_SERVICO INTEGER NOT NULL,
VL_SERVICO NUMERIC(8,2) NOT NULL,
PRIMARY KEY (CD_SERVICO, CD_OS),
FOREIGN KEY (CD_SERVICO) REFERENCES SERVICO (CD_SERVICO),
FOREIGN KEY (CD_OS) REFERENCES OS (CD_OS)
);

CREATE TABLE OS_SERVICO_PRODUTO (
CD_SERVICO INTEGER NOT NULL,
CD_OS INTEGER NOT NULL,
CD_PRODUTO INTEGER NOT NULL,
VL_PRODUTO NUMERIC (8,2) NOT NULL,
QT_SERVICO INTEGER NOT NULL,
PRIMARY KEY (CD_SERVICO, CD_OS, CD_PRODUTO),
FOREIGN KEY (CD_SERVICO,  CD_OS) REFERENCES OS_SERVICO (CD_SERVICO,  CD_OS),
FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO (CD_PRODUTO)
);
